fitur_add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend')

]

fitur_prof/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

fitur_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

fitur_update_status/urls.py
from django.conf.urls import url
from .views import index, update_status

urlpatterns = [
	url(r'^$', index, name='index'),
    url(r'^update_status', update_status, name='update_status'),
]

proyek1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import fitur_add_friend.urls as add_friend
import fitur_update_status.urls as update_status
import fitur_prof.urls as prof
import fitur_stats.urls as stats
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status,namespace='update-status')),
    url(r'^prof/', include(prof,namespace='prof')),
    url(r'^stats/', include(stats,namespace="stats")),
	url(r'^add_friend/', include(add_friend,namespace='add_friend')),
    url(r'^$', RedirectView.as_view(url='/prof/', permanent=True)), 
]

fitur_add_friend/models.py
from django.db import models

# Create your models here.

class Friend(models.Model):
    name = models.CharField(max_length=30)
    URL = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)
	
    def __str__(self):
	    return self.name

fitur_prof/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
	name = models.CharField(max_length=250)
	birthday = models.CharField(max_length=200)
	gender = models.CharField(max_length=200)
	expertise = models.TextField(max_length=200)
	description = models.CharField(max_length=200)
	email = models.CharField(max_length=200)

fitur_stats/models.py
from django.db import models

# Create your models here.

fitur_update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required' : 'Tolong isi input ini',
        'invalid' : 'Isi input ini dengan url',
    }
    attrs = {
        'class' : 'form-control'
    }

    name = forms.CharField(label='Nama', required=True, max_length=30, widget=forms.TextInput(attrs=attrs))
    URL = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs))

fitur_update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi status disini',
    }
    status_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'How Are you today?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

fitur_add_friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend
from datetime import datetime

# Create your views here.

def index(request):
    response = {'author': "Linked-uS"}
    response['friend_form'] = Friend_Form
    friend_dict = Friend.objects.all().values()
    response['friend_dict'] = convert_queryset_into_json(friend_dict)
    html = 'add_friend.html'
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        friend = Friend(name=request.POST['name'], URL=request.POST['URL'])
        friend.save()
        return HttpResponseRedirect('/add_friend')
    else:
        return HttpResponseRedirect('/add_friend')

def convert_queryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

fitur_prof/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from datetime import datetime, date
from fitur_prof.models import Profile

# Create your views here.
name = 'Linked-Us' #TODO implement your name here
birthdate = "5 October 2017" #TODO implement your birthday
# birthdate = birth_date.strftime('%d %B %Y')
gender = 'Unknown' #TODO implement your gender
email = 'admin@linkedus.com' #TODO implement your email
desc_profile = "We Help You To Link Each Other"
#TODO implement your expertise minimal 3
expert = ["Django", "Python", "HTML", "CSS"]
def index(request):
    html = 'prof.html'
    profil = Profile(name = name, birthday = birthdate, gender= gender, email = email, description=desc_profile, expertise=expert)
    response = {'name' : profil.name, 'birthday' : profil.birthday, 'gender': profil.gender, 'expertise': profil.expertise,
                'description' : profil.description, 'email': profil.email}
    return render(request, html, response)

fitur_stats/views.py
from django.shortcuts import render
from django.db import models
from fitur_add_friend.models import Friend
from fitur_update_status.models import Status

response = {'author': "Linked-Us"}

# Create your views here.
def index(request):
    html = 'stats/stats.html'
    counting_all_friends = Friend.objects.all().count()
    counting_all_feeds = Status.objects.all().count()
    latest_status = Status.objects.last()
    response['friends'] = counting_all_friends
    response['feeds'] = counting_all_feeds
    response['status'] =latest_status
    return render(request, html, response)

fitur_update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Jeffry Aldi Permana" #TODO Implement yourname
    status = Status.objects.all()
    response['status'] = status
    html = 'update_status.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def update_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

fitur_add_friend/templates/add_friend.html
{% extends "layout/bases.html" %}

{% block form %}
<br>
<br>
<br>
  <section name="form">
    <h2 class="textcol">Add Friend</h2>
    <form class="textcol" id="form" method="POST" action="{% url 'add_friend:add_friend' %}">
      {% csrf_token %}
      {{ friend_form }}
      <br>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </section>

{% endblock %}

{% block table %}

<h3 class="textcol">List Friend</h3>
{% for friend_data in friend_dict %}
<div class="textcol">
  <div class="col-md-4 col-xs-4">
    {{ friend_data.name }}
  </div>
  <div class="col-md-4 col-xs-4">
    <a href={{ friend_data.URL}} target="_blank">{{ friend_data.URL }}</a>
  </div>
  <div class="col-md-4 col-xs-4">
    <i>Added {{ friend_data.created_date|date:"d N Y" }} {{ friend_data.created_date|time:"H:i:s" }}</i>
  </div>
</div>
{% endfor %}

{% endblock %}

fitur_add_friend/templates/layout/bases.html
<!DOCTYPE html>
<style>
.textcol{
    color: white;
  }
</style>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Add_Friend">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <title>
      {% block title %} {{author}} Add Friend {% endblock %}
    </title>
  </head>
  <body style="background-color: #33495E">
    <header>
      {% include "partials/header.html" %}
    </header>
    <content>
      <div class="container">
        {% block form %}
          <!-- form goes here -->
        {% endblock %}
      </div>
      <div class="container">
        {% block table %}
          <!-- table goes here -->
        {% endblock %}
      </div>
    </content>
    <br />
    <footer>
          <!-- TODO Block Footer dan include footer.html -->
          {% block footer %}
          {% include "partials/footer.html" %}
          {% endblock %}
      </footer>

      <!-- Jquery n Bootstrap Script -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

fitur_prof/templates/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<style>
body{
  padding-top: 50px;
}
.textcol{
  color:white;
}
.navbar-static-top {
  margin-bottom: 19px;
}

.img-circle {
    border-radius: 50%;
    margin: 0 auto;
    display:block;
    width: 200px;
}

ul.exprestise {
  padding: 0;
  text-align: center;
}

.expertise li {
  border-radius: 6px;
  display: inline-block;
  background: #00BBFF;
  color: white;
  padding: 5px 10px;
  margin: 2px;
  font-size: 1rem;
}

.expertise li:nth-child(odd) {
  background: #1BD889;
}

/*Textarea not resizeable*/
textarea {
  resize:none
}

.center {
  margin: auto;
}

h3 {
  margin: auto;
}

table, th, td {
    border: 2px solid darkgrey;
}
.subject{
    padding-top: 10px;
    font-size: 20px;
    font-family: "Calibri";
    color: black;
}
.value{
    font-size: 20px;
    font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
    color: snow;
}

#biodata{
    width: 760px;
}


</style>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="PROFILE">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <link href="{%static "css/prof.css"%}" rel="stylesheet" type="text/css">
    <title>
        {% block title %}Linked-uS Profile{% endblock %}
    </title>
</head>

<body style="background-color: #33495E">
    <header>
              {% include "partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

</body>
</html>

fitur_prof/templates/prof.html
{% extends "layout/base.html" %}

{% block content %}
<h2 class="textcol"><b>Profile</b></h2>
<img class="img-circle" src="https://i.imgur.com/jhzx3s9.jpg" alt = "Me">
<h2 class="textcol"><b><center>{{name}}</center></b></h2>
<hr>
<section class="textcol"name="profile">
  <div class="container" id="biodata">
    <div class="row">
      <div class="col-md-4"><h3><b>Birthday</b></h3></div>
      <div class="col-md-8"><h4>: {{birthday}}</h4></div>
    </div>
    <div class="row">
      <div class="col-md-4"><h3><b>Gender</b></h3></div>
      <div class="col-md-8"><h4>: {{gender}}</h4></div>
    </div>
    <div class="row">
      <div class="col-md-3"><h3><b>Expertise</b></h3></div>
      <div class="col-md-1" style="text-align:right"><h4>:</h4></div>
      <div class="col-md-8"><h4>
        <div class="center">
          <ul class="expertise">
            {% for ii in expertise %}
            <li style="font-size:15px"> {{ ii }} </li>
            {% endfor %}
          </ul>
        </div></h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4"><h3><b>Description</b></h3></div>
      <div class="col-md-8"><h4>: {{description}}</h4></div>
    </div>
    <div class="row">
      <div class="col-md-4"><h3><b>Email</b></h3></div>
      <div class="col-md-8"><h4>: {{email}}</h4></div>
    </div>
  </div>
</section>
{% endblock %}

fitur_stats/templates/stats/layout/base.html
{% load staticfiles %}

<!DOCTYPE html>
<style>
     .textcol{
      color: white;
    }   
	#grad {
		height: 1000px;
		background: linear-gradient(to bottom right, #98dafc, #33495E);
	}
</style>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="STATS">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->

    <title>
        {% block title %} {{author}} Stats {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>    
	
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/stats.css' %}" />
	
</head>

<body>
    <body id="grad">
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
      </style>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    </body>

</body>
</html>

fitur_stats/templates/stats/stats.html
{% extends "stats/layout/base.html" %}

{% block content %}
<br>
<br>
<br>
<style>
  .circular-image {
    border-radius:  50%;
  }
  .feed {
	color: #fae596;
	font-size: 35px;
  }
  .friend {
	color: #fae596;
	font-size: 35px;	
  }
  .space-left {
	padding-left:15px;
  }
  .verified {
	color: #334431;
	font-size: 20px;		
  }

</style>
<br>
<div class="container container-rounded">
	<div class="row-fluid">
		<div class="col-xs-12 col-sm-6 col-md-8" style="background-color: aliceblue;">
			<p class="h4">Statistic</p>			
				<center>
					<img src="https://i.imgur.com/jhzx3s9.jpg" alt="my-image" class="circular-image" width="150" height="150"/>
					<p class="h3"><strong>{{author}}<span class="space-left"></span><span class="glyphicon glyphicon-ok-sign verified"></span></strong></p>
				</center>
				<hr>
				<p class="h4">Latest Post</p>
				<div class="alert alert-warning" role="alert">
					<div class="container">
						<div class="row-fluid">
							<table style="width:0%">
								<td><img src="https://i.imgur.com/jhzx3s9.jpg" alt="my-image" class="circular-image" width="50" height="50"/></td>
									<td><p class="h4 text-info">{{author.name}}</p></td>
							</table>    
								<p class="h4 text-dark">{{status.status}}</p>
								<p class="h6 text-secondary">{{status.created_date|date:"d M Y H:i:s"}}</p>
						</div>
					</div>
				</div>
				
		</div>
		<div class="col-xs-6 col-md-4" style="background-color: black;">
			<p class="h3"><font color="yellow"><strong><span class="glyphicon glyphicon-send feed"></span>	{{feeds}} Posts <span class="space-left"></span> <span class="glyphicon glyphicon-user friend"></span> {{friends}} Friends</strong></font></p>
			<br>
			<a class="btn btn-primary" href="#" role="button">Theme 1</a>
			<a class="btn btn-primary" href="#" role="button">Theme 2</a>
			<br>
			<br>
		</div>
	</div>
</div>




{% endblock %}

fitur_update_status/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<style>
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="UPDATE STATUS">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />

    <title>
        {% block title %} Status By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

fitur_update_status/templates/update_status.html
{% extends "layout/base.html" %}
{% block content %}
<style>
.textcol {
    color: white;
    font-size: 24px;
}
textarea {
    resize:none
}

/* animasi colorchange */
@-webkit-keyframes colorchange {
    0% {
        -webkit-text-stroke: 5px #0fb8ad;
    letter-spacing: 0;
    }
  50% {
    -webkit-text-stroke: 7.5px  #1fc8db;
  }
    100% {
        -webkit-text-stroke: 10px  #2cb5e8;
    letter-spacing: 18px;
    }
}
/* styling wrapper form */
#input-list{
  background: linear-gradient(to bottom right, #606062, #393939);
}
/* styling form */
#input-list form{
  width: 400px;
  margin: 50px auto;
  text-align: center;
  position: relative;
  z-index: 1;
  background: blue;
  border: 0 none;
  border-radius: 3px;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
  padding: 20px 30px;
  box-sizing: border-box;
  position: relative;
}
/* styling judul form, apakah arti dari tanda '>' ? */
#input-list form > h2{
  font-size: 1.3em;
  text-transform: uppercase;
  color: #2C3E50;
  margin-bottom: 10px;
}
/* styling form input dan textarea, apakah arti dari tanda ',' ? */
#input-list form > .status-form-input, #input-list form > .status-form-textarea{
  padding: 15px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
    width: 90%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 13px;
}
@media only screen and (max-width: 768px) {
  #input-list form {
      width: 290px;
  }
}

#input-list{
  background: #33495E;
}
#input-list form{
  width: 100%;
  margin: 10px auto;
  text-align: center;
  position: relative;
  z-index: 1;
  background: white;
  border: 0 none;
  border-radius: 3px;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
  padding: 20px 30px;
  box-sizing: border-box;
  position: relative;
}
#input-list form > h2{
  font-size: 1.3em;
  text-transform: uppercase;
  color: #2C3E50;
  margin-bottom: 10px;
}
#input-list form > .status-form-input, #input-list form > .status-form-textarea{
  padding: 15px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
    width: 100%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 13px;
}
#my-list{
  background: linear-gradient(141deg, #0fb8ad 0%, #1fc8db 51%, #2cb5e8 75%);
}
.status-list{
  text-align: left;
  padding-top: 5px;
  padding-left: 10px;
  background: #3C5873;
  position: relative;
  z-index: 15;
  margin-bottom: 30px;
  -webkit-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  -moz-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  -o-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  transition: 0.5s all;
  -webkit-transition: 0.5s all;
  -moz-transition: 0.5s all;
  -o-transition: 0.5s all;
  color: white;
}
.status-list:after{
    content:"";
    display:block;
    height:15px;
    background:#3C5873;
}
.flex{
  display: flex;
  flex-direction: column-reverse;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  margin-right: -15px;
  margin-left: -15px;
}
.flex-item{
  padding: 0 0px;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: 100%;
  width: 100%;
}
.img-circle {
  border-radius: 50%;
  width: 60px;
  height: 60px;
  margin-right: 10px;
}
@media all and (max-width: 768px) {
.flex-item {flex-basis:100%}
}
</style>
<br>
<br>
<h1 class="textcol">Update Status</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:update_status' %}">
            <h2>Input Status</h2>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-status" id="my-status">
    <div class="container">
        <h2 class="textcol">Latest Posts</h2>
        <div class="flex">
            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div class="status-list">
                        <div>
                    		<h4><img class="img-circle" src="https://i.imgur.com/jhzx3s9.jpg" align="left" alt = "Me">Linked-Us</h4>
                    		</div>
                        <div class="status-list-status">
                                {{data.status}}
                            </div>
                        <div class="status-list-date-added">
                                {{data.created_date| date:"d M Y H:i:s"}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Status.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

templates/partials/footer.html
<center>
<p class="textcol">&copy; Created By Linked-Us Team</p>
</center>

templates/partials/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Linked-Us</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/prof/">Profile</a></li>
      <li><a href="/update-status/">Status</a></li>
      <li><a href="/add_friend/">Friends</a></li>
      <li><a href="/stats/">Stats</a></li>
    </ul>
  </div>
</nav>